### ISSUE TITLE
libmambapy requires libsolv

### ISSUE THREAD

**Issue by nicholas-sly** [conda-forge/mamba-feedstock#163] opened 2022-11-02 01:07 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Running this installation through OpenCE on a Power architecture system resulted in the following error:
```
-- Build files have been written to: /opt/conda/conda-bld/mamba-split_1667349061043/work/build
ninja: error: '/opt/conda/conda-bld/mamba-split_1667349061043/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libsolv.so', needed by 'libmambapy/bindings.cpython-39-powerpc64le-linux-gnu.so', missing and no known rule to make it
```

I was able to fix this by adding `libsolv` as a host requirement under libmambapy in the `recipe/meta.yaml` file.

This is based on the open-ce-v1.7.3 tag which uses commit `6aebd7b6aa7cf5c38abdc09332e9739513d5049c`.

### Installed packages

```shell
Irrelevant.
```

### Environment info

```shell
Irrelevant.
```

**Comment by wolfv** [comment] 2022-11-02 12:32
I think the libsolv dependencie should be exported as run-dependency in `libmamba` (through `run_exports`). In turn, the `libmambapy` depends on `libmamba` that depends on `libsolv`. Where are you getting `libsolv` from for this build?

**Comment by npanpaliya** [comment] 2022-11-03 16:21
@nicholas-sly - I'm from Open-CE team and have been seeing this error for past 2 weeks after we released Open-CE 1.7.3. I've this PR https://github.com/open-ce/mamba-feedstock/pull/14/files that addresses libsolv issue. However, on importing libmambapy, I'm seeing another error as follows -
```
>>> import libmambapy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/pai/home/npanpa23/anaconda3/envs/testopence/lib/python3.10/site-packages/libmambapy/__init__.py", line 7, in <module>
    raise e
  File "/mnt/pai/home/npanpa23/anaconda3/envs/testopence/lib/python3.10/site-packages/libmambapy/__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: /lib64/librpmio.so.8: undefined symbol: EVP_md2, version OPENSSL_1_1_0
```
If I build openssl with `-enable-md2` option, then it works.

**Comment by nicholas-sly** [comment] 2022-11-03 17:34
@npanpaliya I was able to install my local build of libmambapy and import it without issue.  My environment installed openssl==1.1.1q as part of creating the conda environment.  The fact that your error mentions a library installed in `/lib64` makes it sound like there is an interaction between the package and the system that isn't adequately defined in the requirements.  FWIW, I'm building with python 3.9, but I don't expect that to be very relevant.

**Comment by npanpaliya** [comment] 2022-11-04 04:52
Yes, correct. Somehow mamba is linking against /lib64/librpmio.so which is I guess unexpected. I'm trying to figure out from where this dependency is coming from.

**Comment by npanpaliya** [comment] 2022-11-04 10:18
I got the cause. libsolv is needed at runtime too for libmambapy.

**Comment by jjerphan** [comment] 2024-08-19 08:13
This was fixed by https://github.com/conda-forge/mamba-feedstock/commit/b6f6b7cfd6a42ef40c629d7369d69443afbb61e6#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR51-R60, even though `run_exports` must instead be used.

Please reopen the issue, shall you still have this issue.

**Closed by jjerphan** 2024-08-19 08:13 UTC
Labels: bug
